= Applied Graph Algorithms
:presenter: Neo4j
:twitter: neo4j
:email: info@neo4j.com
:neo4j-version: 3.5
:currentyear: 2019
:doctype: book
:toc: left
:toclevels: 3
:nextsecttitle: Setup And Cypher Refresher
:nextsect: 1
:currsect: 0
:experimental:
:imagedir: ../img
:manual: http://neo4j.com/docs/operations-manual/3.5

Graph algorithms are used to compute metrics for graphs, nodes, or relationships.
They can provide insights on relevant entities (centralities, ranking) in the graph or inherent structures such as communities (community-detection, graph-partitioning, clustering).
In this course you will learn how to use Neo4j's Graph Data Science library to enhance your graph based applications.

We will start with an existing web application (a simple business reviews website written in React.js) populated with data from the Yelp public dataset in Neo4j. We then work to enhance the existing functionality of the application using graph algorithms.

[NOTE]
====
Don't worry if you're not familiar with React or web development in general, to enhance our application we'll just be changing the Cypher queries used by the already existing application. But feel free to modify the application if you'd like to add more advanced features!
====

++++
<div style="position: relative; overflow: hidden; padding-top: 56.25%; width: 90%">
  <iframe src="https://www.youtube.com/embed/FfW5YCXBnhQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;" allowfullscreen></iframe>
</div>
++++
_Introduction to Graph Algorithms in Neo4j and overview of this course_

== Course Outline

=== link:../part-1[Setup And Cypher Refresher]

[square]
* Review of the dataset used in this course.
* Accessing the Yelp Neo4j Sandbox.
* Overview of the CodeSandbox React application used in the course.
* Connecting the React application to your Neo4j Sandbox instance.
* Verifying configuration and querying the dataset.

Estimated time: _15 minutes_

=== link:../part-2/[Category Hierarchy]

[square]
* Learn about the Overlap Similarity algorithm and how to use it in Neo4j to build a hierarchy of categories.
* Enhance our business reviews application using Overlap Similarity to improve business search.

Estimated time: _30 minutes_

=== link:../part-3[Ordering Search Results]

[square]
* Learn about Similarity algorithms in Neo4j.
* Use Pearson Similarity to improve search result ordering in our business reviews application.

Estimated time: _30 minutes_

=== link:../part-4[Most Relevant Reviews]

[square]
* Learn about PageRank and Personalized PageRank.
* Use Personalized PageRank to find more relevant business reviews for users.

Estimated time: _30 minutes_

=== link:../part-5[Photo Recommendations]

[square]
* Learn more about Similarity algorithms in Neo4j.
* Learn about Community Detection and the Label Propagation algorithm.
* Use Jaccard Similarity and Label Propagation to build a photo based business recommendation feature.

Estimated time: _30 minutes_

=== link:../part-6[Summary]

[square]
* Quiz results.
* Review of graph algorithms in Neo4j.
* Overview of resources for learning more and doing more with Graph Algorithms in Neo4j.

Estimated time: _10 minutes_

== Prerequisites

This course focuses on using graph algorithms with Neo4j in an applied environment to enhance functionality of an application. To be successful you should:

* Have completed Introduction to Neo4j course or have equal Cypher proficiency.
* Be familiar with Neo4j Browser.
* Be familiar with the concepts of a web application.

++++
<a class="medium button" href="../part-1/">Start the Course!</a>
++++

ifdef::backend-html5[]
++++
<script>
$( document ).ready(function() {
  Intercom('trackEvent','training-applied-algos-view-part0');
});
</script>
++++
//marketo stuff, navigate to next page
endif::backend-html5[]
