== Setup and Cypher Refresher
:presenter: Neo4j
:twitter: neo4j
:email: info@neo4j.com
:neo4j-version: 3.5
:currentyear: 2019
:doctype: book
:toc: left
:toclevels: 3
:nextsecttitle: Category Hierarchy
:prevsecttitle: About This Course
:nextsect: 2
:currsect: 1
:experimental:
:imagedir: ../img
:manual: http://neo4j.com/docs/operations-manual/3.5

ifdef::backend-html5[]

include::scripts.txt[]

endif::backend-html5[]



This CodeSandbox contains all the code for the application that we'll be building.

https://codesandbox.io/embed/github/neo4j-contrib/applied-graph-algorithms-training/tree/master/react-app[Launch CodeSandbox^]

++++
<div style="position: relative; overflow: hidden; padding-top: 56.25%">
    <iframe src="https://www.youtube.com/embed/NK3yC1cSlVU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;" allowfullscreen></iframe>
</div>
++++
_Overview of the application and connecting it to your Neo4j Sandbox instance_

[#module-3.quiz]
== Check your understanding
=== Question 1

==== Algorithm Understanding: Personalized PR

Which of the following best describe the Personalized PageRank algorithm?

Select the correct answer.
[%interactive]
- [ ] [.false-answer]#It measures similarity of the structural context in which objects occur, based on their relationships with other objects.#
- [ ] [.required-answer]#It's a variation of the PageRank algorithm that is biased towards a set of source nodes#
- [ ] [.false-answer]#It computes the influence of a node by measuring the number of the immediate neighbors and also all other nodes in the network that connect to the node under consideration through these immediate neighbors#
- [ ] [.false-answer]#It's a variation of the PageRank algorithm that reduces the bias that PageRank has towards assigning higher scores to nodes with relationships from nodes that have few outgoing relationships.#

== Question 2
==== Running the algorithm in Neo4j

What is the default value of the `dampingFactor` used by the PageRank procedure?

Select the correct answer.
[%interactive]
- [ ] [.false-answer]#0.15#
- [ ] [.required-answer]#0.85#
- [ ] [.false-answer]#0.70#
- [ ] [.false-answer]#0.12#

== Summary

You should now be able to:
[square]
* Use the Personalized Pagerank graph algorithm with Neo4j

== Grade Quiz and Continue 

++++
<a class="next-section medium button" href="../part-4/">Continue to Module 4</a>
++++

ifdef::backend-html5[]

include::scripts-end.txt[]
++++
<script>
$( document ).ready(function() {
  Intercom('trackEvent','training-applied-algos-view-part1');
});
</script>
++++

endif::backend-html5[]


