== Photo Based Gallery Recomendations
:presenter: Neo4j
:twitter: neo4j
:email: info@neo4j.com
:neo4j-version: 3.5
:currentyear: 2019
:doctype: book
:toc: left
:toclevels: 3
:nextsecttitle: Summary
:prevsecttitle: Relevant Reviews
:nextsect: 5
:currsect: 4
:experimental:
:imagedir: ../img
:manual: http://neo4j.com/docs/operations-manual/3.5

ifdef::backend-html5[]

include::scripts.txt[]

endif::backend-html5[]


++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/m0GrcuM8yvg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++

In this section we'll learn how to use the Label Propagation algorithm to recommend photos.


Copy the following command into the query pane of the Neo4j Browser and execute it:

[source, cypher]
----
:play https://guides.neo4j.com/sandbox/applied_graph_algorithms/05_photo_recommendations.html
----

[NOTE]
====
.Useful Resources

* https://neo4j.com/docs/graph-algorithms/current/algorithms/label-propagation/[Label Propagation^]
====

=== Solution

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/WxJRuYpQLiQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
++++


[#module-4.quiz]
== Check your understanding
=== Question 1

==== Algorithm Understanding: LPA

Which category of algorithms best describes LPA?

Select the correct answer.
[%interactive]
- [ ] [.false-answer]#Centrality#
- [ ] [.false-answer]#Similarity & ML Workflow#
- [ ] [.required-answer]#Community Detection#
- [ ] [.false-answer]#Pathfinding and Search#

== Question 2

==== Running the algorithm in Neo4j

Which voting mechanism does Neo4j's Label Propagation algorithm use?

Select the correct answers.
[%interactive]
- [ ] [.false-answer]#Random Walk Method#
- [ ] [.required-answer]#Pull Method#
- [ ] [.false-answer]#Push Method#
- [ ] [.false-answer]#Modularity Optimization Method#

== Summary

You should now be able to:
[square]
* TODO: summary info here

== Grade Quiz and Continue 

++++
<a class="next-section medium button" href="../part-5/">Continue to Module 5</a>
++++

ifdef::backend-html5[]

include::scripts-end.txt[]
++++
<script>
$( document ).ready(function() {
  Intercom('trackEvent','training-applied-algos-view-part4');
});
</script>
++++

endif::backend-html5[]