= Photo Based Gallery Recomendations
:presenter: Neo4j
:twitter: neo4j
:email: info@neo4j.com
:neo4j-version: 3.5
:currentyear: 2019
:doctype: book
:toc: left
:toclevels: 3
:nextsecttitle: Summary
:prevsecttitle: Relevant Reviews
:nextsect: 6
:currsect: 5
:prevsect: 4
:experimental:
:imagedir: ../img
:manual: http://neo4j.com/docs/operations-manual/3.5

++++
<div style="position: relative; overflow: hidden; padding-top: 56.25%; width: 90%;">
  <iframe src="https://www.youtube.com/embed/Rf-dlMCKRlg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;" allowfullscreen></iframe>
</div>
++++
_Similarity algorithms and Label Propagation overview_

In this section you will use the Label Propagation algorithm to recommend photos.

[NOTE]
====
.Useful Resources

* https://neo4j.com/docs/graph-algorithms/current/algorithms/label-propagation/[Label Propagation^]
====

== Exercise

. In Neo4j Browser, perform the steps in the  Neo4j Browser guide section *Photo Recommendations*. (:play applied_graph_algorithms/05_photo_recommendations.html)
. In CodeSandbox, edit the `FETCH_PHOTO_RECOMMENDATIONS` Cypher query in `src/exercises/exercise4.js` to recommend businesses whose photos belong to the same community.
. Save this file.
. In the CodeSandbox Browser, click *Photos* and select five random photos. Then the application presents restaurants based upon the photos selected.

== Solution

If you get stuck, watch this video for a walk-through of the solution:

++++
<div style="position: relative; overflow: hidden; padding-top: 56.25%; width: 90%;">
  <iframe src="https://www.youtube.com/embed/FV0LznTB364" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;" allowfullscreen></iframe>
</div>
++++
_Photo based recommendations solution_

[#module-5.quiz]
== Check your understanding
=== Question 1

=== Algorithm Understanding: LPA

Which category of algorithms best describes LPA?

Select the correct answer.
[%interactive]
- [ ] [.false-answer]#Centrality#
- [ ] [.false-answer]#Similarity & ML Workflow#
- [ ] [.required-answer]#Community Detection#
- [ ] [.false-answer]#Pathfinding and Search#

=== Question 2

=== Running the algorithm in Neo4j

Which voting mechanism does Neo4j's Label Propagation algorithm use?

Select the correct answer.
[%interactive]
- [ ] [.false-answer]#Random Walk Method#
- [ ] [.required-answer]#Pull Method#
- [ ] [.false-answer]#Push Method#
- [ ] [.false-answer]#Modularity Optimization Method#

== Summary

You should now be able to:
[square]
* Use the Jaccard similarity algorithm.
* Use the Label Propagation Community Detection algorithm with Neo4j.

== Grade Quiz and Continue

++++
<a class="next-section medium button" href="../part-6/">Continue to Module 6</a>
++++
