asciidoctor -T _templates_v2 adoc/00_AboutThisCourse.adoc -o html/00_AboutThisCourse.html
asciidoctor -T _templates_v2 adoc/01_IntroductionToGraphDatabases.adoc -o html/01_IntroductionToGraphDatabases.html
asciidoctor -T _templates_v2 adoc/02_IntroductionToNeo4j.adoc -o html/02_IntroductionToNeo4j.html
asciidoctor -T _templates_v2 adoc/03_SettingUpYourDevelopmentEnvironment.adoc -o html/03_SettingUpYourDevelopmentEnvironment.html
asciidoctor -T _templates_v2 adoc/04_IntroductionToCypher.adoc -o html/04_IntroductionToCypher.html
asciidoctor -T _templates_v2 adoc/05_GettingMoreOutOfQueries.adoc -o html/05_GettingMoreOutOfQueries.html
asciidoctor -T _templates_v2 adoc/06_CreatingNodesAndRelationships.adoc -o html/06_CreatingNodesAndRelationships.html
asciidoctor -T _templates_v2 adoc/07_GettingMoreOutOfNeo4j.adoc -o html/07_GettingMoreOutOfNeo4j.html
asciidoctor -T _templates_v2 adoc/08_Summary.adoc -o html/08_Summary.html
