
= Neo4j Administration
:presenter: Neo Technology
:twitter: neo4j
:email: info@neotechnology.com
:neo4j-version: 3.5
:currentyear: 2019
:doctype: book
:toc: left
:toclevels: 3
:nextsecttitle: Intro to Neo4j
:nextsect: 1
:currsect: 0
:experimental:
:imagedir: ../img
:manual: http://neo4j.com/docs/operations-manual/3.5
//:imagedir: https://s3-us-west-1.amazonaws.com/data.neo4j.com/neo4j-admin/img

== About this course

This course introduces you to Neo4j and some of the most common administration tasks for a production Neo4j application using *Neo4j Enterprise Edition 3.5*.

This course is intended for administrators.

This self-paced training should take you 6-7 hours to complete if you perform all of the hands-on exercises in the course.  You need not complete the course in one session. At then end of each module are a set of review questions and we keep track of which modules you answered the questions correctly. If you answer all of the review questions correctly, we will email you a _Certificate of Completion_ for this online training.

We have set up a discussion area in our https://community.neo4j.com/c/general/online-training[Neo4j Community Site], if you run into problems in the course and need assistance. You should register on the community site  where you can view other questions and answers for students taking our online training courses. The _Neo4j Community Site_ is an  excellent resource for answering many types of questions posed by other users of Neo4j.

There are six modules in this course. Most modules have hands-on exercises you should complete as well as a set of review questions at the end. In order to perform the hands-on exercises for this course, you will need to install the Enterprise Edition of Neo4j which is covered in the module, _Overview of Neo4j Administration_. For the module, _Causal Clustering in Neo4j_ you will need to install Docker.  We have provided an estimate of how long each module should take you to complete if you perform the hands-on exercises.

== link:../part-1/[Introduction to Neo4j]

[square]
* Describe the components and benefits of the Neo4j Graph Platform.

Estimated time: _15 minutes_

== link:../part-2/[Overview of Neo4j Administration]

[square]
* Describe common application architectures that use Neo4j.
* Determine which edition of Neo4j to use.
* Download a specific Neo4j version.
* Determine which deployment option to use.
* Describe the administrative tasks for Neo4j.
* Install Neo4j Enterprise Edition.

Estimated time: _45 minutes_

== link:../part-3/[Managing a Neo4j Database]

[square]
* Start a Neo4j instance.
* Stop the Neo4j instance.
* Set the password for the _neo4j_ user.
* Copy a Neo4j database.
* Modify the location for a Neo4j database.
* Check the consistency of a Neo4j database.
* Create scripts for modifying a Neo4j database.
* Manage plugins for a Neo4j database.
* Configure ports used by the Neo4j instance.
* Perform an online backup of a Neo4j database.
* Create a database with the import tool.

Estimated time: _90 minutes_

== link:../part-4/[Causal Clustering in Neo4j]

[square]
* Describe why you would use clusters.
* Describe the components of a  cluster.
* Configure and use a cluster.
* Seed a cluster with data.
* Monitor and manage core servers in the cluster.
* Monitor and manage read replica servers in the cluster.
* Back up a cluster.

Estimated time: _90 minutes_

== link:../part-5/[Security in Neo4j]

[square]
* Describe what security means for an application.
* Configure a Neo4j instance to use LDAP as the authentication provider.
* Describe how to secure data-in-transit.
* Describe how to secure data-at-rest.
* Configure and use security auditing.

Estimated time: _60 minutes_

== link:../part-6/[Monitoring Neo4j]

[square]
* Describe the categories of monitoring and measurement you can perform with Neo4j.
* Monitor:
** queries
** transactions
** connections
** memory usage
* Manage log files.
* Manage the collection of Neo4j metrics.
* Use JMX queries.

Estimated time: _90 minutes_


== link:../part-7/[Summary]

[square]
* Quiz results.
* Resources to learn more.
* Course feedback.

++++
<a class="medium button" href="../part-1/">Start the Course!</a>
++++

ifdef::backend-html5[]
++++
<script>
$( document ).ready(function() {
  Intercom('trackEvent','training-admin-view-part0');
});
</script>
++++
//marketo stuff, navigate to next page
endif::backend-html5[]

