
= Causal Clustering in Neo4j
:presenter: Neo Technology
:twitter: neo4j
:email: info@neotechnology.com
:neo4j-version: 3.5
:currentyear: 2018
:doctype: book
:toc: left
:toclevels: 3
:experimental:
//:imagedir: https://s3-us-west-1.amazonaws.com/data.neo4j.com/neo4j-admin/img
:imagedir: ../img


++++
	<script type='text/javascript'>
	var loc = window.location;
	if (loc.hostname == "neo4j.com" && loc.search.indexOf("aliId=") == -1 ) {
	 loc.pathname = "/graphacademy/online-training/XXXX/"	
	}
	document.write(unescape("%3Cscript src='//munchkin.marketo.net/munchkin.js' type='text/javascript'%3E%3C/script%3E"));
	</script>
	<script>Munchkin.init('773-GON-065');</script>
++++

== About this module

Now that you have gained experience managing a Neo4j instance and database , you will learn how to create and manage Neo4j Causal Clusters.

At the end of this module, you should be able to:
[square]
* Describe why you would use Neo4j Causal Clusters.
* Describe the components of a Neo4j Causal Cluster.
* Configure and use a Neo4j Causal Cluster.
* Seed a Causal Cluster from an existing Neo4j database.
* Secure communication between components of a Neo4j Causal Cluster.

== What is Causal Clustering?



== Summary

You should now be able to:

[square]

