

= Introduction to Neo4j
:presenter: Neo Technology
:twitter: neo4j
:email: info@neotechnology.com
:neo4j-version: 4.0
:currentyear: 2020
:doctype: book
:toc: left
:toclevels: 3
:nextsecttitle: Neo4j is a Graph Database
:nextsect: 1
:currsect: 0
:experimental:
:imagedir: https://s3-us-west-1.amazonaws.com/data.neo4j.com/intro-neo4j/img
:manual: http://neo4j.com/docs/developer-manual/current
:manual-cypher: {manual}/cypher

ifdef::backend-html5[]
include::scripts.txt[]
endif::backend-html5[]

== About this course

This course introduces you to the Neo4j graph database and how to use Cypher to access data in the graph.

This course is intended for developers, architects,  and data scientists. You need not have programming experience to take this training.

This self-paced training should take you 2 days to complete if you perform all of the hands-on exercises in the course.

We have set up a discussion area in our https://community.neo4j.com/c/general/online-training[Neo4j Community Site], if you run into problems in the course and need assistance. You should register on the community site  where you can view other questions and answers for students taking our online training courses. The _Neo4j Community Site_ is an  excellent resource for answering many types of questions posed by other users of Neo4j.

There are XX modules in this course. Most modules have hands-on exercises you should complete and all modules have a set of review questions at the end. The hands-on exercises in this course can be completed in the cloud using Neo4j Auro or a Neo4j Sandbox, or in Neo4j Desktop. We have provided an estimate of how long each module should take you to complete if you perform the hands-on exercises.

== link:../part-1/[Introduction to Graph Databases]

*TBD*
[square]
* Describe what a graph database is.
* Describe how to model relational data in a property graph model.

Estimated time: _30 minutes_

== link:../part-2/[Introduction to Neo4j]

[square]
* Describe the Neo4j Graph Platform and its components.
* Describe the features and benefits of Neo4j.

Estimated time: _30 minutes_

== link:../part-3/[Setting Up Your Development Environment]

[square]
* Set up your development environment for performing the hands-on exercises of this course which is one of:
** Neo4j Sandbox
** Neo4j Desktop

Estimated time: _30 minutes_

== link:../part-4/[Introduction to Cypher]

[square]
* Use `MATCH` to retrieve nodes from the graph.
* Use `MATCH` to retrieve relationships from the graph.
* Use `MATCH` to retrieve properties from the graph.

Estimated time: _60 minutes_

== link:../part-5/[Getting More Out of Queries]

[square]
* Use the `WHERE` clause for queries.
* Control query processing.
* Control how results are returned.
* Work with Cypher dates and lists.

Estimated time: _90 minutes_

== link:../part-6/[Creating Nodes and Relationships]

[square]
* Create, update, and delete nodes and properties of nodes.
* Create, update, and delete relationships and properties of relationships.
* Merge data in the graph.

Estimated time: _90 minutes_

== link:../part-7/[Getting More Out of Neo4j]

[square]
* Use parameters.
* Define constraints in the graph.
* Profile and monitor query execution. 
* Define indexes in the graph.
* Import relational data into the graph.

Estimated time: _90 minutes_

== link:../part-8/[Summary]

[square]
* Quiz results. 
* Resources to learn more.
* Course feedback.

++++
<a class="medium button" href="../part-1/">Start the Course!</a>
++++

ifdef::backend-html5[]
include::scripts-end.txt[]
++++
<script>
$( document ).ready(function() {
  Intercom('trackEvent','training-introv2-view-part1');
});
</script>
++++
//marketo stuff, navigate to next page
endif::backend-html5[]
