

= Data Science with Neo4j
:presenter: Neo Technology
:twitter: neo4j
:email: info@neotechnology.com
:neo4j-version: 3.4.4
:currentyear: 2018
:doctype: book
:toc: left
:toclevels: 3
:nextsecttitle: Setting Up Development Environment
:nextsect: 1
:currsect: 0
:experimental:
:imagedir: https://s3-us-west-1.amazonaws.com/data.neo4j.com/intro-neo4j/img
:manual: http://neo4j.com/docs/developer-manual/current
:manual-cypher: {manual}/cypher

== About this course

This course introduces you to using Neo4j as part of your Data Science and Machine Learning workflows.
We're going to learn how to do this with the help of the https://aminer.org/citation[aminer.org citation dataset^].
This dataset contains papers, authors, and citations from DBLP - a computer science bibliography website.

This course is intended for data scientists and data analysts.

This self-paced training should take you three hours to complete if you perform all of the hands-on exercises in the course.

We have set up a discussion area in our https://community.neo4j.com/c/general/online-training[Neo4j Community Site], if you run into problems in the course and need assistance.
You should register on the community site  where you can view other questions and answers for students taking our online training courses.
The _Neo4j Community Site_ is an  excellent resource for answering many types of questions posed by other users of Neo4j.

There are four modules in this course.
Most modules have hands-on exercises you should complete and all modules have a set of review questions at the end.
The hands-on exercises in this course can be completed in a Neo4j Sandbox or in Neo4j Desktop.
We have provided an estimate of how long each module should take you to complete if you perform the hands-on exercises.

== link:../part-1/[Setting Up Your Development Environment]

[square]
* Set up your Neo4j Sandbox development environment for performing the hands-on exercises of this course
* Set up your Google Colabatory environment for running Jupyter notebooks in this course

Estimated time: _30 minutes_

== link:../part-2/[Exploratory Data Analysis]

[square]
* Query a database for its schema
* Return and chart the number of node labels and relationship types using matplotlib
* Build and plot a histogram of papers and their citations using pandas and matplotlib

Estimated time: _30 minutes_

== link:../part-3/[Recommendations]

[square]
* find potential collaborators for an author
* find relevant papers about a topic for an author

Estimated time: _45 minutes_


== link:../part-4/[Predictions]

[square]
* Describe what link prediction is
* Use the link prediction functions in Neo4j
* Understand the challenges when building machine learning models on graph data
* Build a link prediction classifier using scikit-learn with features derived from the Neo4j Graph Algorithms library

Estimated time: _60 minutes_



== link:../part-5/[Summary]

[square]
* Quiz results.
* Resources to learn more.
* Course feedback.

++++
<a class="medium button" href="../part-1/">Start the Course!</a>
++++

//ifdef::backend-html5[]
//include::scripts-end.txt[]
//++++
//<script>
//$( document ).ready(function() {
//  Intercom('trackEvent','training-introv2-view-part1');
//});
//</script>
//++++
//marketo stuff, navigate to next page
//endif::backend-html5[]
