

= Data Science with Neo4j
:presenter: Neo Technology
:twitter: neo4j
:email: info@neotechnology.com
:neo4j-version: 3.4.4
:currentyear: 2018
:doctype: book
:toc: left
:toclevels: 3
:nextsecttitle: Data Science with Neo4j
:nextsect: 2
:currsect: 0
:experimental:
:imagedir: https://s3-us-west-1.amazonaws.com/data.neo4j.com/intro-neo4j/img
:manual: http://neo4j.com/docs/developer-manual/current
:manual-cypher: {manual}/cypher

ifdef::backend-html5[]
include::scripts.txt[]
endif::backend-html5[]

== About this course

This course introduces you to using Neo4j as part of your Data Science and Machine Learning workflows.
We're going to learn how to do this with the help of the https://aminer.org/citation[aminer.org citation dataset^].
This dataset contains papers, authors, and citations from DBLP - a computer science bibliography website.

This course is intended for data scientists and data analysts.

This self-paced training should take you three hours to complete if you perform all of the hands-on exercises in the course.

We have set up a discussion area in our https://community.neo4j.com/c/general/online-training[Neo4j Community Site], if you run into problems in the course and need assistance.
You should register on the community site  where you can view other questions and answers for students taking our online training courses.
The _Neo4j Community Site_ is an  excellent resource for answering many types of questions posed by other users of Neo4j.

There are four modules in this course.
Most modules have hands-on exercises you should complete and all modules have a set of review questions at the end.
The hands-on exercises in this course can be completed in a Neo4j Sandbox or in Neo4j Desktop.
We have provided an estimate of how long each module should take you to complete if you perform the hands-on exercises.

== link:../part-1/[Introduction to Data Science with Neo4j]

[square]
* Describe what a graph database is.
* Describe how to model relational data in a property graph model.

Estimated time: _30 minutes_

== link:../part-2/[Setting Up Your Development Environment]

[square]
* Set up your Neo4j Sandbox development environment for performing the hands-on exercises of this course which is one of:

Estimated time: _30 minutes_

== link:../part-3/[Exploratory Data Analysis]

[square]
* Set up your development environment for performing the hands-on exercises of this course which is one of:
** Neo4j Sandbox
** Neo4j Desktop

Estimated time: _30 minutes_

== link:../part-4/[Predictions]

[square]
* Use `MATCH` to retrieve nodes from the graph.
* Use `MATCH` to retrieve relationships from the graph.
* Use `MATCH` to retrieve properties from the graph.

Estimated time: _60 minutes_

== link:../part-5/[Recommendations]

[square]
* Use the `WHERE` clause for queries.
* Control query processing.
* Control how results are returned.
* Work with Cypher dates and lists.

Estimated time: _90 minutes_


== link:../part-6/[Summary]

[square]
* Quiz results. 
* Resources to learn more.
* Course feedback.

++++
<a class="medium button" href="../part-1/">Start the Course!</a>
++++

//ifdef::backend-html5[]
//include::scripts-end.txt[]
//++++
//<script>
//$( document ).ready(function() {
//  Intercom('trackEvent','training-introv2-view-part1');
//});
//</script>
//++++
////marketo stuff, navigate to next page
//endif::backend-html5[]
