= Recommendations
:presenter: Neo Technology
:twitter: neo4j
:email: info@neotechnology.com
:neo4j-version: 3.4.4
:currentyear: 2018
:doctype: book
:toc: left
:toclevels: 3
:prevsecttitle: Exploratory Data Analysis
:prevsect: 3
:currsect: 4
:nextsecttitle: Predictions
:nextsect: 5
:experimental:
:imagedir: https://s3-us-west-1.amazonaws.com/data.neo4j.com/intro-neo4j/img
:manual: http://neo4j.com/docs/developer-manual/current
:manual-cypher: {manual}/cypher

ifdef::backend-html5[]

include::scripts.txt[]

endif::backend-html5[]


== About this module

In this module we'll learn how to explore the data in the citation dataset that we'll be using in this course.
We'll be querying Neo4j and processing the results using tools in the Python ecosystem.

At the end of this module, you should be able to:
[square]
* Query a database for its schema
* Return and chart the number of node labels and relationship types using matplotlib
* Build and plot a histogram of papers and their citations using pandas and matplotlib


=== Tools

We'll be using the following tools in this course:

==== pandas

https://pandas.pydata.org/[pandas^] is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.

==== Matplotlib

https://matplotlib.org/[Matplotlib^] is a Python 2D plotting library which produces publication quality figures in a variety of hardcopy formats and interactive environments across platforms.


==== py2neo

The https://py2neo.org/v4/[py2neo^] driver enables data scientists to easily integrate Neo4j with tools in the Python Data Science ecosystem like pandas and matplotlib.
It does this by providing functions that translate the results of queries into data structures used by numpy and pandas.


[#module-2.quiz]
== Check your understanding
=== Question 1

What are some of the benefits provided by the Neo4j Graph Platform?

Select the correct answers.
[%interactive]
- [ ] [.required-answer]#Database clustering#
- [ ] [.required-answer]#ACID#
- [ ] [.required-answer]#Index free adjacency#
- [ ] [.required-answer]#Optimized graph engine#

=== Question 2

What libraries are available for the Neo4j Graph Platform?

Select the correct answers.
[%interactive]
- [ ] [.required-answer]#APOC#
- [ ] [.false-answer]#JGraph#
- [ ] [.required-answer]#Graph Algorithms#
- [ ] [.required-answer]#GraphQL#

=== Question 3

What are some of the language drivers that come with Neo4j out of the box?

Select the correct answers.
[%interactive]
- [ ] [.required-answer]#Java#
- [ ] [.false-answer]#Ruby#
- [ ] [.required-answer]#Python#
- [ ] [.required-answer]#JavaScript#


== Summary

You should now be able to:
[square]
* Describe the components and benefits of the Neo4j Graph Platform.

== Grade Quiz and Continue 

++++
<a class="next-section medium button" href="../part-3/">Continue to Module 3</a>
++++

//ifdef::backend-html5[]
//
//include::scripts-end.txt[]
//++++
//<script>
//$( document ).ready(function() {
//  Intercom('trackEvent','training-introv2-view-part2');
//});
//</script>
//++++
//
//endif::backend-html5[]
