= Introduction to Neo4j

== Exercises for Introduction to Neo4j image:https://avatars3.githubusercontent.com/u/201120[width=50]

In this Browser Guide, you will find instructions for the Exercises of this course.  
You perform these Exercises using a live version of the Neo4j Database Server (Desktop or Sandbox).
Some exercises include optional (Taking it further) steps that you can complete to gain more experience with Cypher.


Select the Exercise you want to complete:

pass:a[<a play-topic='{guides}/01.html'>Exercise 1</a>]
pass:a[<a play-topic='{guides}/02.html'>Exercise 2</a>]
pass:a[<a play-topic='{guides}/03.html'>Exercise 3</a>]
pass:a[<a play-topic='{guides}/04.html'>Exercise 4</a>]
pass:a[<a play-topic='{guides}/05.html'>Exercise 5</a>]
pass:a[<a play-topic='{guides}/06.html'>Exercise 6</a>]
pass:a[<a play-topic='{guides}/07.html'>Exercise 7</a>]
pass:a[<a play-topic='{guides}/08.html'>Exercise 8</a>]
pass:a[<a play-topic='{guides}/09.html'>Exercise 9</a>]
pass:a[<a play-topic='{guides}/10.html'>Exercise 10</a>]
pass:a[<a play-topic='{guides}/11.html'>Exercise 11</a>]
pass:a[<a play-topic='{guides}/12.html'>Exercise 12</a>]
pass:a[<a play-topic='{guides}/13.html'>Exercise 13</a>]
pass:a[<a play-topic='{guides}/14.html'>Exercise 14</a>]
pass:a[<a play-topic='{guides}/15.html'>Exercise 15</a>]
pass:a[<a play-topic='{guides}/16.html'>Exercise 16</a>]

*Important:* If you make a mistake when modifying the database during an Exercise, each Exercise will provide a Cypher script you can execute to revert the database to its state before you started an Exercise.

== Go to the appropriate Exercise Guide listed on the previous page
