

= Introduction to Neo4j
:presenter: Neo Technology
:twitter: neo4j
:email: info@neotechnology.com
:neo4j-version: 3.4.4
:currentyear: 2018
:doctype: book
:toc: left
:toclevels: 3
:experimental:
:imagedir: https://s3-us-west-1.amazonaws.com/data.neo4j.com/intro-neo4j/img
:manual: http://neo4j.com/docs/developer-manual/current
:manual-cypher: {manual}/cypher

++++
	<script type='text/javascript'>
	var loc = window.location;
	if (loc.hostname == "neo4j.com" && loc.search.indexOf("aliId=") == -1 ) {
	 loc.pathname = "/graphacademy/online-training/XXXX/"	
	}
	document.write(unescape("%3Cscript src='//munchkin.marketo.net/munchkin.js' type='text/javascript'%3E%3C/script%3E"));
	</script>
	<script>Munchkin.init('773-GON-065');</script>
++++

== About this course

This course introduces you to graph databases and how to use Neo4j and Cypher to query and update a Neo4j database. 

This course is intended for developers, administrators, architects, data scientists, and data analysts. You need not have programming experience to take this training.

This training should take you seven hours to complete if you perform all of the hands-on exercises in the course.

There are seven modules in this course. Most modules have hands-on exercises you should complete and all modules have a set of review questions at the end. The hands-on exercises in this course can be completed in a Neo4j Sandbox or in Neo4j Desktop. We have provided an estimate of how long each module should take you to complete if you perform the hands-on exercises.

== Introduction to Graph Databases

[square]
* Describe what a graph database is.

Estimated time: _30 minutes_

== Introduction to Neo4j

[square]
* Describe the Neo4j Graph Platform and its components.
* Describe the features and benefits of Neo4j.

Estimated time: _30 minutes_

== Setting Up Your Development Environment

[square]
* Set up your development environment for performing the hands-on exercises of this course which is one of:
** Neo4j Sandbox
** Neo4j Desktop

Estimated time: _30 minutes_

== Introduction to Cypher

[square]
* Use `MATCH` to retrieve nodes from the graph.
* Use `MATCH` to retrieve relationships from the graph.
* Use `MATCH` to retrieve properties from the graph.

Estimated time: _60 minutes_

== Getting More Out of Queries

[square]
* Use the `WHERE` clause for queries.
* Control query processing.
* Control how results are returned.
* Work with Cypher dates and lists.

Estimated time: _90 minutes_

== Creating Nodes and Relationships

[square]
* Create, update, and delete nodes and properties of nodes.
* Create, update, and delete relationships and properties of relationships.
* Merge data in the graph.

Estimated time: _90 minutes_

== Getting More Out of Neo4j

[square]
* Use parameters.
* Define constraints in the graph.
* Profile and monitor query execution. 
* Define indexes in the graph.
* Import relational data into the graph.

Estimated time: _90 minutes_