= Summary: Introduction to Neo4j
:presenter: Neo Technology
:twitter: neo4j
:email: info@neotechnology.com
:neo4j-version: 3.4.4
:currentyear: 2018
:doctype: book
:toc: left
:toclevels: 3
:prevsect: 7
:prevsecttitle: More
:currsect: 8
:experimental:
:imagedir: https://s3-us-west-1.amazonaws.com/data.neo4j.com/intro-neo4j/img
:manual: http://neo4j.com/docs/developer-manual/current
:manual-cypher: {manual}/cypher

[#module-8.quiz]
== Quiz Results
++++
<span id="quizes-result"></span>
++++

== Course Completion Certificate
++++
<span id="cert-result"></span>
++++

== Course Summary

In this course, you have learned how to:

[square]
* Describe what a graph database is.
* Describe how to model relational data in a property graph model.
* Describe the Neo4j Graph Platform and its components.
* Describe the features and benefits of Neo4j.
* Set up your development environment for performing the hands-on exercises of this course which is one of:
** Neo4j Sandbox
** Neo4j Desktop
* Use `MATCH` to retrieve nodes from the graph.
* Use `MATCH` to retrieve relationships from the graph.
* Use `MATCH` to retrieve properties from the graph.
* Use the `WHERE` clause for queries.
* Control query processing.
* Control how results are returned.
* Work with Cypher dates and lists.
* Create, update, and delete nodes and properties of nodes.
* Create, update, and delete relationships and properties of relationships.
* Merge data in the graph.
* Use parameters.
* Define constraints in the graph.
* Profile and monitor query execution.
* Define indexes in the graph.
* Import relational data into the graph.

== Next steps

There are many resources available to you for learning more about Neo4j and Cypher.

Resources for developers:

https://neo4j.com/developer/resources/

Neo4j Community Site where you can ask or answer questions about Neo4j and discuss with other users:

https://community.neo4j.com

Neo4j documentation:

https://neo4j.com/docs/

Neo4j Sandboxes for experimenting with graphs:

https://sandbox.neo4j.com/?ref=graph-academy

Videos on YouTube:

https://www.youtube.com/channel/UCvze3hU6OZBkB1vkhH2lH9Q

GitHub repository:

https://github.com/neo4j-contrib

Neo4j events all over the world:

https://neo4j.com/events/world/all/

Neo4j online and classroom training:

https://neo4j.com/graphacademy/

Graph Gists for learning more use cases for Neo4j:

https://neo4j.com/graphgists/

Become a Neo4j certified developer:

https://neo4j.com/graphacademy/neo4j-certification/

[NOTE]
The certification exam tests you on content from this course. You can take the certification multiple times until you pass!

Attend a Neo4j meetup:

https://www.meetup.com/topics/neo4j/

View questions/answers raised about Neo4j:

https://stackoverflow.com/tags/neo4j/hot


== Course feedback

We want your feedback on this course. Please provide your https://goo.gl/forms/BEpb5Dsj6CFTvWiI2[feedback] so we can improve this course.
